import { Sparkles, Clock, AlertTriangle, User, TrendingUp } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import type { AISuggestion } from '@/types/booking';

interface AISuggestionPanelProps {
  suggestions: AISuggestion[];
  onApplySuggestion: (suggestion: AISuggestion) => void;
  isLoading?: boolean;
}

export function AISuggestionPanel({ 
  suggestions, 
  onApplySuggestion, 
  isLoading = false 
}: AISuggestionPanelProps) {
  if (isLoading) {
    return (
      <Card>
        <CardContent>
          <div className="animate-pulse space-y-4">
            <div className="h-4 bg-gray-200 rounded w-3/4"></div>
            <div className="h-3 bg-gray-200 rounded w-full"></div>
            <div className="h-3 bg-gray-200 rounded w-2/3"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (suggestions.length === 0) {
    return (
      <Card>
        <CardContent>
          <div className="text-center py-6">
            <Sparkles className="h-8 w-8 text-gray-400 mx-auto mb-2" />
            <p className="text-gray-600 text-sm">
              AI suggestions will appear as you fill out the form
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  const getIcon = (type: string) => {
    switch (type) {
      case 'best-time': return <Clock className="h-5 w-5" />;
      case 'urgency': return <AlertTriangle className="h-5 w-5" />;
      case 'doctor-recommendation': return <User className="h-5 w-5" />;
      case 'clinic-recommendation': return <TrendingUp className="h-5 w-5" />;
      default: return <Sparkles className="h-5 w-5" />;
    }
  };

  const getColor = (type: string) => {
    switch (type) {
      case 'best-time': return 'text-blue-600 bg-blue-100';
      case 'urgency': return 'text-red-600 bg-red-100';
      case 'doctor-recommendation': return 'text-green-600 bg-green-100';
      case 'clinic-recommendation': return 'text-purple-600 bg-purple-100';
      default: return 'text-medical-600 bg-medical-100';
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return 'text-green-600 bg-green-100';
    if (confidence >= 0.6) return 'text-yellow-600 bg-yellow-100';
    return 'text-red-600 bg-red-100';
  };

  return (
    <Card>
      <CardContent>
        <div className="flex items-center space-x-2 mb-4">
          <div className="p-2 bg-medical-100 rounded-lg">
            <Sparkles className="h-5 w-5 text-medical-600" />
          </div>
          <div>
            <h3 className="font-semibold text-gray-900">AI Suggestions</h3>
            <p className="text-sm text-gray-600">Smart recommendations for your appointment</p>
          </div>
        </div>

        <div className="space-y-4">
          {suggestions.map((suggestion, index) => (
            <div
              key={index}
              className="border border-gray-200 rounded-lg p-4 hover:shadow-sm transition-shadow"
            >
              <div className="flex items-start space-x-3">
                <div className={`p-2 rounded-lg ${getColor(suggestion.type)}`}>
                  {getIcon(suggestion.type)}
                </div>
                
                <div className="flex-1">
                  <div className="flex items-center justify-between mb-2">
                    <h4 className="font-medium text-gray-900">{suggestion.title}</h4>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${getConfidenceColor(suggestion.confidence)}`}>
                      {Math.round(suggestion.confidence * 100)}% confident
                    </span>
                  </div>
                  
                  <p className="text-sm text-gray-600 mb-3">
                    {suggestion.description}
                  </p>
                  
                  {suggestion.action && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => onApplySuggestion(suggestion)}
                      className="text-medical-600 border-medical-300 hover:bg-medical-50"
                    >
                      {suggestion.action.label}
                    </Button>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* AI Disclaimer */}
        <div className="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
          <p className="text-xs text-yellow-800">
            <strong>AI Disclaimer:</strong> These suggestions are generated by AI and should not replace professional medical advice. 
            Always consult with healthcare providers for medical decisions.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}