codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

  flags:
    frontend:
      paths:
        - frontend/src/
      carryforward: true
    
    backend:
      paths:
        - backend/src/
      carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/e2e/**"
  - "**/*.d.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/mockData/**"
  - "**/mocks/**"
