import { Request, Response } from 'express';
import { Types } from 'mongoose';
import AIAssistantService from '../services/AIAssistantService';
import asyncHandler from '../middleware/asyncHandler';
import { AIConversationStatus } from '../models/AIAssistant';

/**
 * @route   POST /api/ai/conversations
 * @desc    Create a new AI conversation
 * @access  Private
 */
export const createConversation = asyncHandler(async (req: Request, res: Response) => {
  const { message } = req.body;

  if (!message || typeof message !== 'string') {
    res.status(400).json({
      success: false,
      message: 'Message is required'
    });
    return;
  }

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const conversation = await AIAssistantService.createConversation(new Types.ObjectId(req.user.userId), message);

  res.status(201).json({
    success: true,
    data: conversation
  });
});

/**
 * @route   POST /api/ai/conversations/:conversationId/messages
 * @desc    Send a message in a conversation
 * @access  Private
 */
export const sendMessage = asyncHandler(async (req: Request, res: Response) => {
  const { conversationId } = req.params;
  const { message } = req.body;

  if (!message || typeof message !== 'string') {
    res.status(400).json({
      success: false,
      message: 'Message is required'
    });
    return;
  }

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  try {
    const { response, conversation } = await AIAssistantService.processUserInput(
      conversationId,
      new Types.ObjectId(req.user.userId),
      message
    );

    res.status(200).json({
      success: true,
      data: {
        response,
        conversation
      },
      meta: {
        disclaimer: 'This is a placeholder response. In a real implementation, this would be generated by an AI model.'
      }
    });
  } catch (error: any) {
    res.status(404).json({
      success: false,
      message: error.message || 'Conversation not found'
    });
  }
});

/**
 * @route   GET /api/ai/conversations
 * @desc    Get all conversations for the current user
 * @access  Private
 */
export const getConversations = asyncHandler(async (req: Request, res: Response) => {
  const { page = '1', limit = '20', status } = req.query;

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const result = await AIAssistantService.listConversations(
    new Types.ObjectId(req.user.userId),
    {
      page: parseInt(page as string, 10),
      limit: parseInt(limit as string, 10),
      status: status as AIConversationStatus
    }
  );

  res.status(200).json({
    success: true,
    data: result.data,
    pagination: result.pagination
  });
});

/**
 * @route   GET /api/ai/conversations/:conversationId
 * @desc    Get a single conversation by ID
 * @access  Private
 */
export const getConversation = asyncHandler(async (req: Request, res: Response) => {
  const { conversationId } = req.params;

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const conversation = await AIAssistantService.getConversation(conversationId, new Types.ObjectId(req.user.userId));

  if (!conversation) {
    res.status(404).json({
      success: false,
      message: 'Conversation not found'
    });
    return;
  }

  res.status(200).json({
    success: true,
    data: conversation
  });
});

/**
 * @route   PATCH /api/ai/conversations/:conversationId/status
 * @desc    Update conversation status
 * @access  Private
 */
export const updateConversationStatus = asyncHandler(async (req: Request, res: Response) => {
  const { conversationId } = req.params;
  const { status } = req.body;

  if (!status || !Object.values(AIConversationStatus).includes(status)) {
    res.status(400).json({
      success: false,
      message: 'Valid status is required'
    });
    return;
  }

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const conversation = await AIAssistantService.updateConversationStatus(
    conversationId,
    new Types.ObjectId(req.user.userId),
    status
  );

  if (!conversation) {
    res.status(404).json({
      success: false,
      message: 'Conversation not found'
    });
    return;
  }

  res.status(200).json({
    success: true,
    data: conversation
  });
});

/**
 * @route   DELETE /api/ai/conversations/:conversationId
 * @desc    Delete a conversation
 * @access  Private
 */
export const deleteConversation = asyncHandler(async (req: Request, res: Response) => {
  const { conversationId } = req.params;

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const deleted = await AIAssistantService.deleteConversation(conversationId, new Types.ObjectId(req.user.userId));

  if (!deleted) {
    res.status(404).json({
      success: false,
      message: 'Conversation not found'
    });
    return;
  }

  res.status(200).json({
    success: true,
    data: {}
  });
});

/**
 * @route   GET /api/ai/conversations/history
 * @desc    Get recent conversation history
 * @access  Private
 */
export const getConversationHistory = asyncHandler(async (req: Request, res: Response) => {
  const { limit = '5' } = req.query;

  if (!req.user) {
    res.status(401).json({
      success: false,
      message: 'Not authenticated'
    });
    return;
  }

  const history = await AIAssistantService.getConversationHistory(
    new Types.ObjectId(req.user.userId),
    parseInt(limit as string, 10)
  );

  res.status(200).json({
    success: true,
    data: history
  });
});

/**
 * @route   POST /api/ai/symptom-checker
 * @desc    Check symptoms (placeholder implementation)
 * @access  Private
 */
export const checkSymptoms = asyncHandler(async (req: Request, res: Response) => {
  const { symptoms, duration, severity } = req.body;

  if (!symptoms || !Array.isArray(symptoms) || symptoms.length === 0) {
    res.status(400).json({
      success: false,
      message: 'At least one symptom is required'
    });
    return;
  }

  // This is a placeholder response
  // In a real implementation, this would call an AI service to analyze symptoms
  const response = {
    possibleConditions: [
      {
        name: 'Common Cold',
        confidence: 'medium',
        description: 'A viral infection of the upper respiratory tract.',
        recommendedActions: [
          'Get plenty of rest',
          'Stay hydrated',
          'Consider over-the-counter cold medicine',
          'Consult a doctor if symptoms persist for more than 10 days'
        ]
      }
    ],
    recommendations: [
      'Get plenty of rest',
      'Drink fluids to stay hydrated',
      'Consider over-the-counter pain relievers if needed',
      'Seek medical attention if symptoms worsen or persist'
    ],
    disclaimer: 'This is not a medical diagnosis. Please consult with a healthcare professional for an accurate assessment of your symptoms.',
    isEmergency: false,
    shouldSeeDoctor: severity === 'severe' || (duration && parseInt(duration) > 7)
  };

  res.status(200).json({
    success: true,
    data: response,
    meta: {
      disclaimer: 'This is a placeholder response. In a real implementation, this would be generated by an AI model analyzing your symptoms.'
    }
  });
});
